[phases.setup]
nixPkgs = ["maven", "openjdk17"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[phases.start]
cmd = "java -Xmx256m -Xms128m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -jar target/nordeste-servicos-0.0.1-SNAPSHOT.jar"

[variables]
JAVA_OPTS = "-Xmx256m -Xms128m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication"
SPRING_PROFILES_ACTIVE = "test"
