[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "java -Xmx256m -Xms128m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -jar target/nordeste-servicos-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# Configurações para economizar recursos
[deploy.env]
JAVA_OPTS = "-Xmx256m -Xms128m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication"
SPRING_PROFILES_ACTIVE = "test" 