[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Configurações para economizar recursos
[deploy.env]
JAVA_OPTS = "-Xmx256m -Xms128m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication"
SPRING_PROFILES_ACTIVE = "test" 